# Generated by Django 6.0.6 on 2026-06-12 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='employment_type',
            field=models.CharField(default='C2C', max_length=20),
        ),
        migrations.AddField(
            model_name='candidate',
            name='role',
            field=models.CharField(default='C2C', max_length=100),
            preserve_default=False,
        ),
    ]
