# Generated by Django 6.0.6 on 2026-06-13 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_candidate_employment_type_candidate_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
