# Generated by Django 6.0.6 on 2026-06-13 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_candidate_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
    ]
